/* =========================================================================
 * Glint AI — PayPal Subscriptions (JS SDK) + Supabase (auth) integration
 * -------------------------------------------------------------------------
 * Wires the pricing cards to PayPal subscription buttons and the login modal
 * to Supabase. Until configured, the UI degrades gracefully (CTA buttons show
 * a hint instead of breaking).
 *
 * Fill in:
 *   1. SUPABASE_URL / SUPABASE_ANON_KEY   — from your Supabase project
 *   2. PAYPAL_CLIENT_ID / PAYPAL_PLANS    — from your PayPal BUSINESS account
 *       (收付款 → 定期付款 → 计划 → 复制 SDK 代码里的 client-id 和 plan_id)
 *
 * The PayPal webhook (api/paypal-webhook.js) writes subscription status back
 * to Supabase `profiles.plan`. See SETUP.md for the full flow.
 * ========================================================================= */

// 通过同源代理 /api/sb 转发（绕过 *.supabase.co 被 GFW 封锁，且无需 Supabase Pro）。
// 站点无论部署在 *.vercel.app 还是绑定的 shortdramapartner.com，均同源可达。
const SUPABASE_URL = (typeof location !== 'undefined' ? location.origin : '') + '/api/sb';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cXVwbWZhYmVsaWlodGxpZ2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwMjEwNzIsImV4cCI6MjEwMTU5NzA3Mn0.kPFGcwl-CCGP8SBXebmBnzUaZcQy5Z5paOyOcVY6k04';

// PayPal subscriptions — copied from the SDK code generated by each plan
const PAYPAL_CLIENT_ID = 'BAAXQXi1cmysWiOuEybXGpWsj1XoEYgQjHjc5z_kW5mHPxKFu45jsRBPWcLhwAUUf0_GueumV1XinIEJpk';
const PAYPAL_PLANS = {
  pro:  'P-8JY348393B145582ENJ2IRFQ',      // Pro $9/mo
  team: 'P-5C811609NL238632RNJ2ITIA'         // Team $29/mo
};
const PAYPAL_ENABLED = PAYPAL_CLIENT_ID.startsWith('BAA') && PAYPAL_PLANS.pro.startsWith('P-');

const hasSupabase = typeof supabase !== 'undefined' && SUPABASE_URL.startsWith('http');
const client = hasSupabase ? supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
let mode = 'login'; // 'login' | 'signup'

/* ---- Render PayPal subscription buttons into the pricing cards ---- */
function loadPaypalSdk(cb) {
  if (window.paypal && window.paypal.Buttons) return cb();
  const s = document.createElement('script');
  s.src = `https://www.paypal.com/sdk/js?client-id=${PAYPAL_CLIENT_ID}&vault=true&intent=subscription`;
  s.onload = cb;
  s.onerror = () => console.warn('PayPal SDK failed to load');
  document.head.appendChild(s);
}

function renderPaypalButtons() {
  if (!PAYPAL_ENABLED) {
    // No config yet — keep the fallback CTA buttons (they hint on click)
    return;
  }
  loadPaypalSdk(() => {
    Object.keys(PAYPAL_PLANS).forEach(plan => {
      const planId = PAYPAL_PLANS[plan];
      const container = document.getElementById('pp-' + plan);
      if (!container || !planId.startsWith('P-') || container.dataset.rendered) return;
      container.dataset.rendered = '1';
      // hide the fallback CTA now that a real PayPal button renders here
      const fallback = document.getElementById('buy' + plan.charAt(0).toUpperCase() + plan.slice(1));
      if (fallback) fallback.style.display = 'none';
      paypal.Buttons({
        style: { shape: 'rect', color: 'gold', layout: 'vertical', label: 'subscribe' },
        createSubscription: (data, actions) => actions.subscription.create({ plan_id: planId }),
        onApprove: () => {
          alert('Subscription started! We are activating your plan now. Log in (or sign up) with the same email to access Pro features.');
        }
      }).render('#pp-' + plan);
    });
  });
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', renderPaypalButtons);
} else {
  renderPaypalButtons();
}

/* ---- Auth modal controls ---- */
function openModal() {
  const m = document.getElementById('authModal');
  if (m) m.style.display = 'flex';
}
function closeModal() {
  const m = document.getElementById('authModal');
  if (m) m.style.display = 'none';
}
window.closeModal = closeModal;

function toggleMode() {
  mode = (mode === 'login') ? 'signup' : 'login';
  document.getElementById('authSubmit').textContent = (mode === 'login') ? 'Log in' : 'Sign up';
  document.getElementById('toggleAuth').textContent =
    (mode === 'login') ? 'Need an account? Sign up' : 'Have an account? Log in';
  document.getElementById('authMsg').textContent = '';
}
window.toggleMode = toggleMode;

document.getElementById('loginBtn')?.addEventListener('click', e => {
  e.preventDefault();
  openModal();
});

/* ---- Magic link (passwordless) ---- */
async function magicLink(e) {
  e.preventDefault();
  const msg = document.getElementById('authMsg');
  if (!client) { msg.textContent = 'Supabase not configured yet — see SETUP.md.'; return; }
  const email = document.getElementById('authEmail').value;
  if (!email) { msg.textContent = 'Enter your email first.'; return; }
  msg.textContent = 'Sending link…';
  const { error } = await client.auth.signInWithOtp({
    email,
    options: { emailRedirectTo: location.href }
  });
  msg.textContent = error ? error.message : 'Check your inbox for the magic link.';
}
window.magicLink = magicLink;

/* ---- Email + password login / signup ---- */
document.getElementById('authForm')?.addEventListener('submit', async (e) => {
  e.preventDefault();
  const msg = document.getElementById('authMsg');
  if (!client) { msg.textContent = 'Supabase not configured yet — see SETUP.md.'; return; }
  const email = document.getElementById('authEmail').value;
  const password = document.getElementById('authPass').value;
  if (!email || !password) { msg.textContent = 'Email and password required.'; return; }
  msg.textContent = (mode === 'login') ? 'Logging in…' : 'Creating account…';

  try {
    const fn = (mode === 'login')
      ? client.auth.signInWithPassword({ email, password })
      : client.auth.signUp({ email, password });
    const { data, error } = await fn;

    if (error) { msg.textContent = error.message; return; }
    msg.textContent = (mode === 'login') ? 'Welcome back!' : 'Account created — confirm your email.';
    await reflectUser(data.user || data.session?.user);
    setTimeout(closeModal, 600);
  } catch (err) {
    msg.textContent = err?.message || 'Login failed. Please try again.';
    console.error(err);
  }
});

/* ---- Logout ---- */
async function doLogout() {
  if (client) await client.auth.signOut();
  const lb = document.getElementById('loginBtn');
  if (lb) { lb.textContent = 'Log in'; lb.onclick = (e) => { e.preventDefault(); openModal(); }; }
  // restore "Get Pro" CTA
  const gp = document.getElementById('getProBtn');
  if (gp) { gp.textContent = 'Get Pro'; gp.href = '#pricing'; }
}
window.doLogout = doLogout;

/* ---- Reflect logged-in user + subscription status ---- */
async function reflectUser(user) {
  if (!user) return;
  const lb = document.getElementById('loginBtn');
  if (lb) {
    lb.textContent = user.email.split('@')[0];
    lb.onclick = (e) => { e.preventDefault(); doLogout(); };
  }
  if (!client) return;
  // `profiles` table gets `plan` written by the PayPal webhook (api/paypal-webhook.js)
  const { data } = await client
    .from('profiles')
    .select('plan')
    .eq('id', user.id)
    .single();
  const plan = data?.plan;
  if (plan && plan !== 'free') {
    const gp = document.getElementById('getProBtn');
    if (gp) { gp.textContent = 'Open app'; gp.href = '#tools'; }
  }
}

/* ---- Session restore on load ---- */
if (client) {
  client.auth.getSession().then(({ data }) => {
    if (data.session) reflectUser(data.session.user);
  });
  client.auth.onAuthStateChange((_event, session) => {
    if (session) reflectUser(session.user);
  });
}
